on: [push]
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: adb exec-out screencap -p > screenshot.png

      - uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot.png
