on: [push]
jobs:
  test:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          force-avd-creation: true
          emulator-options: -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: adb exec-out screencap -p > screencap.png

      - uses: actions/upload-artifact@v3
        with:
          name: screencap
          path: screencap.png

      - run: screencapture screencapture.jpg

      - uses: actions/upload-artifact@v3
        with:
          name: screencapture
          path: screencapture.jpg
